import os.path as path
import imp

cxxtestbuilder_path = '../../cxxtest/build_tools/SCons/cxxtest.py'
cxxtest_path = '../../cxxtest/'

cxxtest = imp.load_source('cxxtest', cxxtestbuilder_path)

env = Environment()

cxxtest.generate(env, CXXTEST_INSTALL_DIR = cxxtest_path)
env.CxxTest('test_index', ['test_index.h', '../src/sphere-index.o'])
env.CxxTest('test_field', ['test_field.h', '../src/sphere-index.o', '../src/sphere-geoind.o', '../src/sphere-type.o', '../src/sphere-field.o'])

